Lidar_front_end:
   lidar_type: 3   # 1 for Livox-avia, 3 for Ouster-OS1-64
   N_SCANS: 6
   using_raw_point: 1
   point_step: 1
   
r3live_common:
   if_dump_log: 0                   # If recording ESIKF update log. [default = 0]
   record_offline_map: 1            # If recording offline map. [default = 1]
   pub_pt_minimum_views: 3          # Publish points which have been render up to "pub_pt_minimum_views" time. [default = 3]
   minimum_pts_size: 0.01           # The minimum distance for every two points in Global map (unit in meter). [default = 0.01] 
   image_downsample_ratio: 1        # The downsample ratio of the input image. [default = 1]
   estimate_i2c_extrinsic: 1        # If enable estimate the extrinsic between camera and IMU. [default = 1] 
   estimate_intrinsic: 1            # If enable estimate the online intrinsic calibration of the camera lens. [default = 1] 
   maximum_vio_tracked_pts: 600     # The maximum points for tracking. [default = 600]
   append_global_map_point_step: 4  # The point step of append point to global map. [default = 4]

r3live_vio:
   camera_intrinsic:
      [383.21994861507153, 0.0, 320,
       0.0, 383.5812690237224, 200,
       0.0, 0.0, 1.0] 
   camera_dist_coeffs: [-0.07153915, -0.0116737, -0.00873085, 0.00792661, 0.0]  #k1, k2, p1, p2, k3
   # # Fine extrinsic value. form camera-LiDAR calibration WL.
   camera_ext_R:
      [0.000,  0.707, -0.707,
       1.000,  0.000,  0.000,
       0.000, -0.707, -0.707]
   camera_ext_t: [-0.18, 0.03, -0.1]

   # Fine extrinsic value. form camera-LiDAR calibration LL (front camera).
   # camera_ext_R:
   #    [0.7071068, -0.5000000,  0.5000000,
   #    -0.7071068, -0.5000000,  0.5000000,
   #     0.0000000, -0.7071068, -0.7071068]
   # Fine extrinsic value. form camera-LiDAR calibration LL (top camera).
   # camera_ext_R:
   #    [0.7071068,  0.1830127,  0.6830127,
   #    -0.7071068,  0.1830127,  0.6830127,
   #    -0.0000000, -0.9659258,  0.2588190]
   # camera_ext_t: [0.1817, 0.1294, -0.290] 
   
r3live_lio:        
   lio_update_point_step: 4   # Point step used for LIO update.  
   max_iteration: 3           # Maximum times of LIO esikf.
   lidar_time_delay: 0        # The time-offset between LiDAR and IMU, provided by user. 
   filter_size_corner: 0.50   
   filter_size_surf: 0.50
   filter_size_surf_z: 0.30
   filter_size_map: 0.30